# config.yaml

# FILE PATHS
data_file_path: "data/mini_project_1_data.csv"
model_dir: "models"
output_dir: "output"

# TASK DEFINITIONS
task_type: "regression"

# DATA DEFINTIONS
identifier_column: "ID"
target_column: "shares"

n_jobs: -1
random_state: 42

# DATA PREPROCESSING
test_size: 0.2

# MODEL TRAINING
search_type: "grid" # "grid", "random", or "bayes"
cv_folds: 5
scoring_metric: r2
n_iter: 10 # only for random/bayes

# MODEL EVALUATION
generate_plots: true
