# config.yaml
# Configuration file for the supervised machine learning pipeline

#######################################################################################################################################
#######################################################################################################################################
# 🌐 GLOBAL SETTINGS
n_jobs: -1
random_state: 42

#######################################################################################################################################
#######################################################################################################################################
# 📁 FILE PATHS
data_file_path: "data/mini_project_1_data.csv"
model_dir: "models"
output_dir: "output"

#######################################################################################################################################
#######################################################################################################################################
# 🎯 TASK DEFINITIONS
task_type: "regression"
debug: false
debug_task_type: "classification"

#######################################################################################################################################
#######################################################################################################################################
# 🧾 DATA DEFINITIONS
identifier_column: "ID"
target_column: "shares"

#######################################################################################################################################
#######################################################################################################################################
# ⚙️ DATA PREPROCESSING
test_size: 0.2
stratify: false

#######################################################################################################################################
#######################################################################################################################################
# 🤖 MODEL TRAINING
resampling_method: null # "null", "SMOTE", "SMOTE-ENN"
hyperparameter_search_type: "grid" # "grid", "random", or "bayes"
n_iter: 10 # only for random/bayes
cv_folds: 5
scoring_metric: r2

#######################################################################################################################################
#######################################################################################################################################
# 📊 MODEL EVALUATION
minimum_precision: null
minimum_recall: null
generate_plots: true
